export const JohnDoeTeacherJWTToken =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidHlwZSI6InRlYWNoZXIiLCJpYXQiOjE2MzQ2Mzk4MjF9.r6u8YIQKMsF5YYzyYSo7iRPpDcOxp4ziERd2D54q4mY';
export const XYZEmployerJWTToken = `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidHlwZSI6ImVtcGxveWVyIiwiaWF0IjoxNjM1MDQ3MDIyfQ.Gk443stxdf9SVul0w-B054lUIkhKFfnGJMQcGfhrE6o`;
export const SaraswatiEmployerJWTToken = `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidHlwZSI6ImVtcGxveWVyIiwiaWF0IjoxNjM1MDQ3MTI1fQ.d_vnwZs-T0GaaD1UQvRciHCwBVzJlGxH0OAeLn3DYIs`;
